fix: remove idea folder
etclabscore/jade-signer-rpc pull request #18
Opened 2019-05-01 18:16 UTC by shanejonas

fixes #17

2019-05-01 20:42 UTC, BelfordZ approved these changes

2019-05-01 20:43 UTC, BelfordZ requested changes
Can we add it to the gitignore as well please?

2019-05-01 21:17 UTC, shanejonas commented
@BelfordZ i noted in the ticket, it is in the `.gitignore`

2019-05-02 06:08 UTC, r8d8 approved these changes

2019-05-02 06:09 UTC, merged